project_id = "qgtcogpbqyjwgeanccto"

[functions.scene-setup-options]
verify_jwt = false

[functions.realtime-session]
verify_jwt = false

[functions.checkout]
verify_jwt = true

[functions.confirm-payment]
verify_jwt = false
